Patch 2ff script to suggest install imagemagick
Imagemagick is soft dependency of farbfeld -- usually user do not need
it, since conversion from jpeg and png -- the most common formats, are
built-it, but in more rare cases, when imagemagick *is* needed,
user-friendly error message apperars, suggesting to install required
package instead just complaining about missing `convert' binary.

diff --git a/2ff b/2ff
--- a/2ff
+++ b/2ff
@@ -24,6 +24,11 @@ image/jpeg)
 	jpg2ff < "$TMP"
 	;;
 *)
+	if [ ! -x /usr/bin/convert ] ; then
+		printf "%s: cant convert from %s -- missing \`convert' program" "$0" "$FORMAT" >&2
+		printf "Run \`apt-get install imagemagick' to install it" >&2
+		exit 1
+	fi
 	convert "$TMP" png:- 2>/dev/null | png2ff 2>/dev/null
 	;;
 esac
